
POST https://schooleg.com/Schooleg/check-phone-status
Content-Type: application/json

{
  "phone": 9934906211
}


###
# Login
POST https://schooleg.com/Schooleg/login
Content-Type: application/json

{
  "role": "Driver",
  "phone": "9934906211",
  "password": "123456"
}

###
GET https://schooleg.com/Schooleg/parents-by-school-phone?phone=1234567890&school_id=66fac9603e512ca16feb7a6d


###
